def get_item_template(slogan_dict, today_str, idx):
    return {"feed_product_type": "kitchen", "item_sku": f"{today_str}-{idx}", "brand_name": "Gifts On Demand",
                      "item_name": slogan_dict["item_name"], "external_product_id": "",
                      "external_product_id_type": "UPC", "item_type": "novelty-coffee-mugs", "standard_price": 19.95,
                      "quantity": 99, "main-image-url": slogan_dict["left_mug_url"],
                      "other-image-url1": slogan_dict["right_mug_url"],
                      "other-image-url2": slogan_dict["microwave_mug_url"],
                      "other-image-url3": slogan_dict["size_example_url"], "other-image-url4": "",
                      "other-image-url5": "", "other-image-url6": "", "other-image-url7": "", "other-image-url8": "",
                      "swatch-image-url": "", "parent_child": "", "parent_sku": "", "relationship_type": "",
                      "variation_theme": "", "update_delete": "", "product_description": "", "manufacturer": "",
                      "part_number": "", "model": "", "closure_type": "",
                      "bullet_point1": "High quality mug makes the perfect gift for everyone.",
                      "bullet_point2": "Printed on only the highest quality mugs. The print will never fade no matter how many times it is washed.",
                      "bullet_point3": "Packaged, and shipped from the USA.",
                      "bullet_point4": "Dishwasher and Microwave safe.",
                      "bullet_point5": "Shipped in a custom made styrofoam package to ensure it arrives perfect. GUARANTEED.",
                      "target_audience_base": "", "catalog_number": "", "specific_uses_keywords1": "",
                      "specific_uses_keywords2": "", "specific_uses_keywords3": "", "specific_uses_keywords4": "",
                      "specific_uses_keywords5": "", "target_audience_keywords1": "", "target_audience_keywords2": "",
                      "target_audience_keywords3": "", "thesaurus_attribute_keywords1": "",
                      "thesaurus_attribute_keywords2": "", "thesaurus_attribute_keywords3": "",
                      "thesaurus_attribute_keywords4": "", "thesaurus_subject_keywords1": "",
                      "thesaurus_subject_keywords2": "", "thesaurus_subject_keywords3": "",
                      "generic_keywords": slogan_dict["keywords"], "platinum_keywords1": "", "platinum_keywords2": "",
                      "platinum_keywords3": "", "platinum_keywords4": "", "platinum_keywords5": "",
                      "country_as_labeled": "", "fur_description": "", "occasion": "", "number_of_pieces": "",
                      "scent_name": "", "included_components": "", "color_name": "white", "color_map": "",
                      "size_name": "", "material_type": "", "style_name": "", "power_source_type": "", "wattage": "",
                      "special_features1": "", "special_features2": "", "special_features3": "",
                      "special_features4": "", "special_features5": "", "pattern_name": "",
                      "lithium_battery_voltage": "", "compatible_devices1": "", "compatible_devices2": "",
                      "compatible_devices3": "", "compatible_devices4": "", "compatible_devices5": "",
                      "compatible_devices6": "", "compatible_devices7": "", "compatible_devices8": "",
                      "compatible_devices9": "", "compatible_devices10": "", "wattage_unit_of_measure": "",
                      "included_features": "", "lithium_battery_voltage_unit_of_measure": "", "length_range": "",
                      "shaft_style_type": "", "specification_met": "", "breed_recommendation": "", "directions": "",
                      "number_of_sets": "", "blade_edge_type": "", "blade_material_type": "",
                      "material_composition": "", "mfg_maximum": "", "mfg_minimum": "", "website_shipping_weight": "",
                      "website_shipping_weight_unit_of_measure": "", "item_shape": "",
                      "item_display_length_unit_of_measure": "", "item_display_width_unit_of_measure": "",
                      "item_display_height_unit_of_measure": "", "item_display_length": "", "item_display_width": "",
                      "item_display_depth": "", "item_display_height": "", "item_display_diameter": "",
                      "item_display_weight": "", "item_display_weight_unit_of_measure": "", "volume_capacity_name": 11,
                      "volume_capacity_name_unit_of_measure": "ounces", "item_height": "", "item_length": "",
                      "item_width": "", "size_map": "", "weight_recommendation_unit_of_measure": "", "width_range": "",
                      "maximum_weight_recommendation": "", "item_dimensions_unit_of_measure": "",
                      "fulfillment_center_id": "", "package_height": "", "package_width": "", "package_length": "",
                      "package_dimensions_unit_of_measure": "", "package_weight": "",
                      "package_weight_unit_of_measure": "", "energy_efficiency_image_url": "",
                      "warranty_description": "", "cpsia_cautionary_statement": "", "cpsia_cautionary_description": "",
                      "fabric_type": "", "import_designation": "", "legal_compliance_certification_metadata": "",
                      "legal_compliance_certification_expiration_date": "", "item_volume": "",
                      "item_volume_unit_of_measure": "", "specific_uses_for_product": "", "country_string": "",
                      "country_of_origin": "", "legal_disclaimer_description": "", "usda_hardiness_zone1": "",
                      "usda_hardiness_zone2": "", "are_batteries_included": "", "item_weight": "",
                      "batteries_required": "", "battery_type1": "", "battery_type2": "", "battery_type3": "",
                      "item_weight_unit_of_measure": "", "number_of_batteries1": "", "number_of_batteries2": "",
                      "number_of_batteries3": "", "lithium_battery_energy_content": "", "lithium_battery_packaging": "",
                      "lithium_battery_weight": "", "number_of_lithium_ion_cells": "",
                      "number_of_lithium_metal_cells": "", "battery_cell_composition": "", "battery_weight": "",
                      "battery_weight_unit_of_measure": "", "lithium_battery_energy_content_unit_of_measure": "",
                      "lithium_battery_weight_unit_of_measure": "", "supplier_declared_dg_hz_regulation1": "",
                      "supplier_declared_dg_hz_regulation2": "", "supplier_declared_dg_hz_regulation3": "",
                      "supplier_declared_dg_hz_regulation4": "", "supplier_declared_dg_hz_regulation5": "",
                      "hazmat_united_nations_regulatory_id": "", "safety_data_sheet_url": "",
                      "lighting_facts_image_url": "", "flash_point": "", "external_testing_certification1": "",
                      "external_testing_certification2": "", "external_testing_certification3": "",
                      "external_testing_certification4": "", "external_testing_certification5": "",
                      "external_testing_certification6": "", "ghs_classification_class1": "",
                      "ghs_classification_class2": "", "ghs_classification_class3": "",
                      "california_proposition_65_compliance_type": "", "california_proposition_65_chemical_names1": "",
                      "california_proposition_65_chemical_names2": "", "california_proposition_65_chemical_names3": "",
                      "california_proposition_65_chemical_names4": "", "california_proposition_65_chemical_names5": "",
                      "merchant_shipping_group_name": "", "list_price": "", "map_price": "",
                      "product_site_launch_date": "", "merchant_release_date": "", "condition_type": "",
                      "restock_date": "", "fulfillment_latency": "", "condition_note": "", "product_tax_code": "",
                      "sale_price": "", "sale_from_date": "", "sale_end_date": "", "item_package_quantity": "",
                      "max_aggregate_ship_quantity": "", "offering_can_be_gift_messaged": "",
                      "offering_can_be_giftwrapped": "", "is_discontinued_by_manufacturer": "",
                      "max_order_quantity": "", "number_of_items": "", "offering_start_date": "",
                      "offering_end_date": ""}

def get_amazon_data():
    pass